### ISSUE TITLE
Explorer: Не работает клавиша Backspace для перехода на родительскую папку

### ISSUE THREAD

**Issue by denis2dev** [OSGreentea/Greentea#56]
![explorer - press backspase](https://cloud.githubusercontent.com/assets/20608739/17237879/3021774a-555f-11e6-9816-b07f32eda9f3.png)

**Comment by denis2dev** [comment]
Done and Tested in "bootcd-72043-dbg"
https://jira.reactos.org/browse/CORE-11710

**Comment by xdev31** [comment]
Fixed so I closed :)
