### ISSUE TITLE
Explorer: Не правильные &-клавиши в меню Проводника на русском

### ISSUE THREAD

**Issue by denis2dev** [OSGreentea/Greentea#72]
![explorer - hot key menu](https://cloud.githubusercontent.com/assets/20608739/17455604/aabf3a52-5bc5-11e6-9edd-740c261a6d99.png)

**Comment by r57zone** [comment]
Fixed https://github.com/OSGreentea/Kernel/commit/9dd649780646b767465aefa1038794e041865b77
