### ISSUE TITLE
Explorer: Не правильное имя столбца 'Name' в Проводнике

### ISSUE THREAD

**Issue by denis2dev** [OSGreentea/Greentea#73]
![explorer - incorrect column name name](https://cloud.githubusercontent.com/assets/20608739/17460992/532dd1d4-5c85-11e6-8419-d4e4996fc41a.png)

**Comment by xdev31** [comment]
We dont copy text of Microsoft

**Comment by PeyTy** [comment]
@xdev31 But we can copy from Ubuntu! How Ubuntu names those columns?

**Comment by xdev31** [comment]
@PetTy oh yeah!

**Comment by r57zone** [comment]
Fixed https://github.com/OSGreentea/Kernel/commit/a2e52ef0b521564d4c96857cee6985bd5282cb4d

**Comment by PeyTy** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;TqA3p75V&#x2F;8-ui-ux-fixes"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> UI&#x2F;UX Fixes</a>
